// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "serverlessswapi",
    "version": "1"
  },
  "paths": {
    "/api/personas": {
      "post": {
        "summary": "crearRegistro",
        "description": "",
        "operationId": "crearRegistro.post./api/personas",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "get": {
        "summary": "leerRegistros",
        "description": "",
        "operationId": "leerRegistros.get./api/personas",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/swagger": {
      "get": {
        "summary": "swagger",
        "description": "",
        "operationId": "swagger.get./swagger",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/swagger.json": {
      "get": {
        "summary": "swaggerjson",
        "description": "",
        "operationId": "swaggerjson.get./swagger.json",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};